import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { CheckItem, ScheduleRow, buildScheduleRows } from '../../utils/receipt-calculation';

@Component({
  selector: 'app-check-grid',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './check-grid.component.html',
  styleUrls: ['./check-grid.component.scss']
})
export class CheckGridComponent implements OnChanges {


  // ── Cheque rows (generated by parent, auto-dated) ─────────────
  @Input() checks: CheckItem[] = [];

  // ── Fixed-row values (from shared form object) ────────────────
  @Input() bank: string = '';
  @Input() adminFeeTotal: number = 0;
  @Input() adminFeeReference: string = '';
  @Input() depositTotal: number = 0;
  @Input() depositReference: string = '';
  @Input() penaltyTotal: number = 0;
  @Input() penaltyCause: string = '';
  @Input() penaltyReference: string = '';
  @Input() periodFrom: string = '';
  @Input() periodTo: string = '';

  // ── Backend invoice total — footer shows THIS, not a subtotal ─
  @Input() invoiceTotal: number = 0;

  // ── Outputs ──────────────────────────────────────────────────
  @Output() checksChange = new EventEmitter<CheckItem[]>();
  @Output() totalAmountChange = new EventEmitter<number>();
  @Output() grandTotalChange = new EventEmitter<number>();

  rows: ScheduleRow[] = [];

  // ── Derived ──────────────────────────────────────────────────
  get hasAdditionalCharge(): boolean {
    return !!this.penaltyCause;
  }
onReferenceInput(row: ScheduleRow, value: string): void {
  if (row.rowType !== 'check') return; // only cheque rows are editable

  row.referenceNo = value;

  const updatedChecks = this.checks.map(c =>
    c.lineNo === row.lineNo ? { ...c, checkNo: value } : c
  );

  this.checks = updatedChecks;
  this.checksChange.emit(updatedChecks);
}
  get chequeSum(): number {
    return Math.round(this.checks.reduce((acc, c) => acc + (c.amount || 0), 0) * 100) / 100;
  }

  /** Sum of every row currently on the schedule (Admin Fee + Deposit + Additional + Cheques). */
  get scheduleTotal(): number {
    return Math.round((
      this.adminFeeTotal +
      this.depositTotal +
      (this.hasAdditionalCharge ? this.penaltyTotal : 0) +
      this.chequeSum
    ) * 100) / 100;
  }

  get isOverBudget(): boolean {
    return this.invoiceTotal > 0 && this.scheduleTotal > this.invoiceTotal + 0.005;
  }

  get varianceAmount(): number {
    return Math.round((this.invoiceTotal - this.scheduleTotal) * 100) / 100;
  }

  ngOnChanges(_changes: SimpleChanges): void {
    this.rebuildRows();
    this.grandTotalChange.emit(this.scheduleTotal);
  }

  private rebuildRows(): void {
    this.rows = buildScheduleRows({
      adminFeeTotal: this.adminFeeTotal,
      adminFeeReference: this.adminFeeReference,
      depositTotal: this.depositTotal,
      depositReference: this.depositReference,
      penaltyTotal: this.penaltyTotal,
      penaltyCause: this.penaltyCause,
      penaltyReference: this.penaltyReference,
      bank: this.bank,
      periodFrom: this.periodFrom,
      periodTo: this.periodTo,
      checks: this.checks,
    });
  }

  /** Only cheque-row amounts are editable; edits write back into the persisted checks array. */
  onAmountInput(row: ScheduleRow, value: number): void {
    if (!row.editable) return;

    const amount = Math.round((value || 0) * 100) / 100;
    row.amount = amount;

    const target = this.checks.find(c => c.checkNo === row.referenceNo);
    if (target) target.amount = amount;

    this.checksChange.emit(this.checks);
    this.totalAmountChange.emit(this.chequeSum);
    this.grandTotalChange.emit(this.scheduleTotal);
  }
}